### ISSUE TITLE
Cannot call system fonts on macOS

### ISSUE THREAD

**Issue by zartre** [DobaKung/IT-KMITL-Latex#2]
`\setmainfont[Scale=1.3]{Angsana New}` gives error `Package fontspec Error: The font "Angsana New" cannot be found.`

**Comment by sagelga** [comment]
Is this issue fixed? @DobaKung

**Comment by kavinvin** [comment]
Actually, this issue should be closed because macOS doesn't have Angsana anyway. We have another problem instead though.
