### ISSUE TITLE
Error on Project Report: Cannot find 'full-report.bcf'

### ISSUE THREAD

**Issue by phongsathorn1** [DobaKung/IT-KMITL-Latex#23]
**Error log**

INFO - This is Biber 2.15
INFO - Logfile is 'full-report.blg'
ERROR - Cannot find 'full-report.bcf'!
INFO - ERRORS: 1

**Comment by zartre** [comment]
May you try with BibTeX instead of Biber?

**Comment by phongsathorn1** [comment]
It's solved!
Sorry for my misreading.
